### ISSUE TITLE
Handle posting networkPolicy objects

### ISSUE THREAD

**Issue by andrewkrug** [abonas/kubeclient#203]
Does this gem support creating network policy objects in this style for example?

I can do it with kubeclient...

```
apiVersion: extensions/v1beta1                                                                      
kind: NetworkPolicy                                                                                 
metadata:                                                                                           
 name: standard-ingress-policy                                                                      
 namespace: fd5ce1e9481667af26bf6a78697d8ccf4fe2d172                                                
spec:                                                                                               
  podSelector:                                                                                      
  ingress:                                                                                          
    - from:                                                                                         
        - namespaceSelector:                                                                        
            matchLabels:                                                                            
                tier: frontend  
```
