### ISSUE TITLE
Can't create a config map with nested properties.

### ISSUE THREAD

**Issue by zeroDivisible** [abonas/kubeclient#265]
Hi,

I'm just starting to use the library so this may as well be user error, but I can't seem to be able to create a config using `kubeclient`.

Normally, the map can be represented as an yml file:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample.map
data:
  service.properties: |
    my.service.sample.property="hey k8!"
```

I was using the following code to create it using `kubeclient`:

```
config_map = Kubeclient::Resource.new
config_map.metadata = {}
config_map.metadata.name = "sample.map"
config_map.metadata.namespace = "default"
config_map.data = {}
config_map.data['service.properties'] = {}
config_map.data['service.properties']['my.service.sample.property'] = 'hey k8!'
```

However, when trying to create the object with `kube_client.create_config_map(config_map)`, I'm getting:

```
*** KubeException Exception: ConfigMap in version "v1" cannot be handled as a ConfigMap: [pos 82]: json: expect char '"' but got char '{'
```
