### ISSUE TITLE
Error loading config from kube config when it contains credentials created by gcloud

### ISSUE THREAD

**Issue by tanner-bruce** [abonas/kubeclient#337]
When a kube config file contains credentials created from `gcloud container clusters get-credentials ...` it has a time in the users block. Loading this config file fails. I've narrowed down the issue to this specific piece of code: https://github.com/abonas/kubeclient/blob/master/lib/kubeclient/config.rb#L28, particularly `YAML.safe_load(File.read(filename)`. Changing this to `YAML.load` fixes the issue, but I'm not sure that is the best approach. I've submitted an upstream bug report in psych, which can be found here: https://github.com/ruby/psych/issues/362

```
irb(main):005:0> config = Kubeclient::Config.read(ENV['KUBECONFIG'] || ENV['HOME'] + '/.kube/config')
Traceback (most recent call last):
       16: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/visitor.rb:6:in `accept'
       15: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/visitor.rb:16:in `visit'
       14: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
       13: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
       12: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:336:in `each_slice'
       11: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:336:in `each'
       10: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
        9: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:32:in `accept'
        8: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/visitor.rb:6:in `accept'
        7: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/visitor.rb:16:in `visit'
        6: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
        5: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:60:in `deserialize'
        4: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/scalar_scanner.rb:62:in `tokenize'
        3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/scalar_scanner.rb:123:in `parse_time'
        2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/class_loader.rb:28:in `load'
        1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/psych/class_loader.rb:97:in `find'
Psych::DisallowedClass (Tried to load unspecified class: Time)
```

```
users:
- name: gke_username
  user:
    auth-provider:
      config:
        access-token: redacted
        cmd-args: config config-helper --format=json
        cmd-path: /Users/tannerbruce/opt/google-cloud-sdk/bin/gcloud
        expiry: 2018-07-07T18:25:36Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
